### ISSUE TITLE
关于魔法网络的解决

### ISSUE THREAD

**Issue by MyMaskKing** [MyMaskKing/MyMaskKing.github.io#3]
# 免费域名注册

⭐

**可挂载Cloudflare**

[ggff.net](https://ggff.net/)域名：[https://customer.l53.net/](https://customer.l53.net/)

DPDNS.ORG域名：[https://dash.domain.digitalplat.org/panel/main](https://dash.domain.digitalplat.org/panel/main)

[ip-ddns.com](https://ip-ddns.com/)域名：[https://www.cloudns.net/main/dashboard/dns/](https://www.cloudns.net/main/dashboard/dns/)

**未来可挂载Cloudflare**

zone.id域名：[https://my.zone.id/subdomains](https://my.zone.id/subdomains)

**低价域名可挂载Cloudflare**

[https://www.youtube.com/watch?v=5XKcLBFBIog&t=2s](https://www.youtube.com/watch?v=5XKcLBFBIog&t=2s)

# 域名解析检测

## Ping查询_专业精准的IP库服务商_IPIP

> [https://tools.ipip.net/ping.php](https://tools.ipip.net/ping.php)

## **域名的DNS检测**：

> [https://myssl.com/dns_check.html#dns_check](https://myssl.com/dns_check.html#dns_check)

![Image](https://raw.githubusercontent.com/MyMaskKing/MyMaskKing.github.io/main/assets/images/关于魔法网络的解决/img_5f5f810086.png)

## **在线Tcping(网站测试)**

> [https://www.itdog.cn/tcping/hello.mymaskking.ggff.net](https://www.itdog.cn/tcping/hello.mymaskking.ggff.net)

![Image](https://raw.githubusercontent.com/MyMaskKing/MyMaskKing.github.io/main/assets/images/关于魔法网络的解决/img_51ebe8f302.png)

## **虚拟信息生成器**

⭐

-   **虚拟信息生成器1：**[https://www.meiguodizhi.com/jp-address](https://www.meiguodizhi.com/jp-address)

-   **虚拟信息生成器2：**[https://www.shenfendaquan.com/](https://www.shenfendaquan.com/)

![Image](https://raw.githubusercontent.com/MyMaskKing/MyMaskKing.github.io/main/assets/images/关于魔法网络的解决/img_dab73be8d7.png)

## **我的IP信息：**[https://www.ipaddress.my/?lang=zh_CN](https://www.ipaddress.my/?lang=zh_CN)

![Image](https://raw.githubusercontent.com/MyMaskKing/MyMaskKing.github.io/main/assets/images/关于魔法网络的解决/img_8870d3bf12.png)

# 域名解析

⭐

-   **cloudflare域名解析**：[https://dash.cloudflare.com/login](https://dash.cloudflare.com/login)

-   [**He.net**](https://he.net/) **DNS域名解析：**[https://ipv6.he.net/certification/login.php?redir=%2Fcertification%2Fcert-main.php](https://ipv6.he.net/certification/login.php?redir=%2Fcertification%2Fcert-main.php)

-   **华为云国际版域名解析**：[https://console-intl.huaweicloud.com/dns/?agencyId=7c10feef2ef147f6b06149e7b0e6a172&region=ap-southeast-1&locale=zh-cn#/dns/publiczones](https://console-intl.huaweicloud.com/dns/?agencyId=7c10feef2ef147f6b06149e7b0e6a172&region=ap-southeast-1&locale=zh-cn#/dns/publiczones)

# 接码平台

⭐

-   **SMS_MAN(接码平台)：**[https://sms-man.com/cn](https://sms-man.com/cn)

-   **老牌接码平台：**[https://sms-activate.org/cn#](https://sms-activate.org/cn#)

# Cloudflare节点优选

⭐

-   **CloudFlare 公共 Cname 域名：**[https://www.wetest.vip/page/cloudflare/cname.html](https://www.wetest.vip/page/cloudflare/cname.html)

-   **CloudFlare公共优选Cname域名地址1：**[点我](https://www.wetest.vip/)

-   **CloudFlare公共优选Cname域名地址2：**[点](https://www.wetest.vip/)[我](https://blog.nbvil.com/nat/saasip/)

-   **CloudFlare优质IP：**[点我](https://stock.hostmonit.com/CloudFlareYes)

# 🌟🌟🌟Google无限邮箱规则

⭐

-   **在用户名中添加点号（**`**.**`**）**

-   Gmail 会忽略用户名中的点号，因此以下地址都指向同一个邮箱：

-   [`username@gmail.com`](mailto:username@gmail.com)

-   [`user.name@gmail.com`](mailto:user.name@gmail.com)

-   [`u.s.e.r.n.a.m.e@gmail.com`](mailto:u.s.e.r.n.a.m.e@gmail.com)

-   您可以根据需要自由添加点号，邮件仍会发送到您的主邮箱。

-   **在用户名后添加加号（**`**+**`**）和任意字符**

-   您可以在用户名后添加加号和任意字符，创建别名。例如：

-   `username+`[`shopping@gmail.com`](mailto:shopping@gmail.com)

-   `username+`[`work@gmail.com`](mailto:work@gmail.com)

-   `username+`[`newsletter@gmail.com`](mailto:newsletter@gmail.com)

-   这些别名的邮件都会投递到 [`username@gmail.com`](mailto:username@gmail.com)。这种方式有助于您根据邮件来源设置过滤器或分类。

-   **注意**：部分网站可能不支持含有加号的邮箱地址，注册时请留意相关提示。

-   **更改邮箱后缀为** `**@**`[`**googlemail.com**`](https://googlemail.com/)

-   Gmail 的另一个有效后缀是 `@`[`googlemail.com`](https://googlemail.com/)，因此以下地址也指向同一个邮箱：

-   [`username@gmail.com`](mailto:username@gmail.com)

-   [`username@googlemail.com`](mailto:username@googlemail.com)

# 🌟🌟🌟临时邮箱

⭐

**临时邮箱**[**https://temp-mail.org/zh**](https://temp-mail.org/zh)**（注意每次打开都要使用隐私模式）**

# 🌟免费Linux机器

⭐

**Google出品的虚拟机：**[https://idx.google.com/](https://idx.google.com/)

# AI大模型部署

⭐

[https://www.youtube.com/watch?v=HDTHDIxHej4](https://www.youtube.com/watch?v=HDTHDIxHej4)

## portainer(docker容器管理:已汉化)

# 好玩的docker应用

⭐

-   [https://github.com/coracoo/awesome_docker_cn?tab=readme-ov-file#docker%E7%AE%A1%E7%90%86](https://github.com/coracoo/awesome_docker_cn?tab=readme-ov-file#docker%E7%AE%A1%E7%90%86)

-   [https://github.com/itgoyo/awesome-docker](https://github.com/itgoyo/awesome-docker)

-   [https://iwanlab.com/category/docker-series/](https://iwanlab.com/category/docker-series/)

## portainer(docker容器管理:已汉化)

```
version: '3.1'
services:
  portainer:
    image: 6053537/portainer-ce
    container_name: portainer
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    restart: unless-stopped
```

```
docker-compose -f mogu_portainer.yml up -d
```

> 12位密码设置：XXX123456789

## Halo个人博客（需要的内存太大，放弃）

> 参考链接：[https://blog.vlinyu.com/archives/docker-compose-blog-halo](https://blog.vlinyu.com/archives/docker-compose-blog-halo)

```
version: "3"

services:
  halo:
    image: halohub/halo:1.6.0
    container_name: halo
    restart: on-failure:3
    volumes:
      - ./data:/root/.halo
  #    - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8000:8090"                 # 访问端口
    environment:
      - SERVER_PORT=8090
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.h2.Driver
      - SPRING_DATASOURCE_URL=jdbc:h2:file:~/.halo/db/halo  # 数据保存位置，默认
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=o#DwN&JSa56
      - HALO_ADMIN_PATH=admin       # 管理页面访问地址https://your-domain/{admin-path}
      - HALO_CACHE=level           # 缓存方式memory(内存)/level(本地)/redis（需配置redis）
      - JAVA_OPTS=-Xms256m -Xmx1024m
    networks:
      - mynet

networks:                           # 连接外部网络，方便内部代理
  mynet:
#    external: true
```

## Gmeek个人博客（基于github）

> 教学视频：[点我](https://www.bilibili.com/video/BV1GM4m1m7ZD/?vd_source=aafb688695496c16d63c4b9e07f211b3)  
> github官方网址：[点我](https://github.com/Meekdai/Gmeek)
